# -*- coding: utf-8 -*-
"""HealthCare Analytics For Doctor Visits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T_eN_qgECcX9MW6euAhTDL2Q3lyMpwb-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/1776250375-P2-Healthcare Analytics for Doctor Visits.csv")

# Top five rows
df.head()

# last five rows
df.tail()

#shape
df.shape

df.info()

# statistical information
df.describe()

# checking  null values
df.isnull().sum()

"""### Univariate Analysis: Age Distribution"""

plt.figure(figsize=(8, 6))
sns.histplot(df['age'], kde=True)
plt.title('Distribution of Age')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""**Univariate Analysis: Income Distribution**"""

plt.figure(figsize=(8, 6))
sns.histplot(df['income'], kde=True)
plt.title('Distribution of Income')
plt.xlabel('Income')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""**Univariate Analysis:Gender Distribution**"""

plt.figure(figsize=(7, 5))
sns.countplot(x='gender', data=df, palette='viridis')
plt.title('Count of Gender')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""**univariate Analysis:Doctor Visits Distribution**"""

plt.figure(figsize=(8, 6))
sns.histplot(df['visits'],bins= range(int(df['visits'].max())+2), kde=False,color='pink')
plt.title('Distribution of Doctor visits')
plt.xlabel('Number of visits')
plt.ylabel('count')
plt.xticks(range(int(df['visits'].max())+1))
plt.show()

gender_analysis = (
    df.groupby('gender')['visits']
      .agg(['count', 'mean', 'median'])
      .reset_index()
)

display(gender_analysis)

sns.barplot(
    data=gender_analysis,
    x='gender',
    y='mean',
    color='teal'
)

plt.title('Average Doctor Visits by Gender')
plt.xlabel('Gender')
plt.ylabel('Mean recorded visits')
plt.show()

illness_analysis = (
    df.groupby("illness")["visits"]
      .agg(["count", "mean"])
      .reset_index()
)

display(illness_analysis)

sns.lineplot(
    data=illness_analysis,
    x="illness",
    y="mean",
    marker="o"

)

plt.title("Illness Score vs. Average Doctor Visits")
plt.xlabel("Illness score")
plt.ylabel("Mean recorded visits")
plt.show()

"""### Multivariate Analysis: Correlation Heatmap"""

plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features')
plt.show()

"""### Multivariate Analysis: Age, Income, and Visits"""

plt.figure(figsize=(10, 8))
sns.scatterplot(x='age', y='income', hue='visits', size='visits', data=df, palette='viridis', sizes=(20, 400), alpha=0.6)
plt.title('Age vs Income colored by Number of Visits')
plt.xlabel('Age')
plt.ylabel('Income')
plt.legend(title='Visits')
plt.grid(axis='both', linestyle='--', alpha=0.7)
plt.show()

"""### Multivariate Analysis: Gender, Health, and Visits (Box Plot)"""

plt.figure(figsize=(12, 7))
sns.boxplot(x='gender', y='visits', hue='health', data=df, palette='pastel')
plt.title('Doctor Visits by Gender and Health Status')
plt.xlabel('Gender')
plt.ylabel('Number of Visits')
plt.legend(title='Health Score')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""### Multivariate Analysis: Pairplot of Key Numerical Features"""

numerical_features = ['age', 'income', 'visits', 'illness', 'reduced', 'health']
sns.pairplot(df[numerical_features])
plt.suptitle('Pairwise Relationships of Key Numerical Features', y=1.02) # Adjust suptitle position
plt.show()